/*
 * Phone Backend
 *
 * ## API for managing phones connected to P7M cloud PBX  The purpose of this API is mainly to manage the configuration of phones that use P7M auto provisioning.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContactList {
    #[serde(rename = "contactListId")]
    pub contact_list_id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "lastChange")]
    pub last_change: String,
}

impl ContactList {
    pub fn new(contact_list_id: String, tenant_id: String, name: String, last_change: String) -> ContactList {
        ContactList {
            contact_list_id,
            tenant_id,
            name,
            last_change,
        }
    }
}


