/*
 * Phone Backend
 *
 * ## API for managing phones connected to P7M cloud PBX  The purpose of this API is mainly to manage the configuration of phones that use P7M auto provisioning.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyType {
    #[serde(rename = "NA")]
    NA,
    #[serde(rename = "FORWARD")]
    FORWARD,
    #[serde(rename = "DTMF")]
    DTMF,
    #[serde(rename = "SPEED_DIAL")]
    SPEEDDIAL,
    #[serde(rename = "LINE")]
    LINE,
    #[serde(rename = "BLF")]
    BLF,

}

impl ToString for KeyType {
    fn to_string(&self) -> String {
        match self {
            Self::NA => String::from("NA"),
            Self::FORWARD => String::from("FORWARD"),
            Self::DTMF => String::from("DTMF"),
            Self::SPEEDDIAL => String::from("SPEED_DIAL"),
            Self::LINE => String::from("LINE"),
            Self::BLF => String::from("BLF"),
        }
    }
}

impl Default for KeyType {
    fn default() -> KeyType {
        Self::NA
    }
}




