/*
 * Phone Backend
 *
 * ## API for managing phones connected to P7M cloud PBX  The purpose of this API is mainly to manage the configuration of phones that use P7M auto provisioning.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewContactEntry {
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "officeNumber")]
    pub office_number: String,
    #[serde(rename = "mobileNumber")]
    pub mobile_number: String,
    #[serde(rename = "otherNumber")]
    pub other_number: String,
    #[serde(rename = "line")]
    pub line: i32,
    #[serde(rename = "autoDivert")]
    pub auto_divert: String,
}

impl NewContactEntry {
    pub fn new(display_name: String, office_number: String, mobile_number: String, other_number: String, line: i32, auto_divert: String) -> NewContactEntry {
        NewContactEntry {
            display_name,
            office_number,
            mobile_number,
            other_number,
            line,
            auto_divert,
        }
    }
}


