/*
 * Phone Backend
 *
 * ## API for managing phones connected to P7M cloud PBX  The purpose of this API is mainly to manage the configuration of phones that use P7M auto provisioning.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewPhoneAccount {
    #[serde(rename = "accountNumber")]
    pub account_number: i32,
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "missedCallLog")]
    pub missed_call_log: bool,
}

impl NewPhoneAccount {
    pub fn new(account_number: i32, user_name: String, display_name: String, password: String, label: String, missed_call_log: bool) -> NewPhoneAccount {
        NewPhoneAccount {
            account_number,
            user_name,
            display_name,
            password,
            label,
            missed_call_log,
        }
    }
}


