/*
 * Phone Backend
 *
 * ## API for managing phones connected to P7M cloud PBX  The purpose of this API is mainly to manage the configuration of phones that use P7M auto provisioning.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewPhoneKey {
    #[serde(rename = "keyGroup")]
    pub key_group: String,
    #[serde(rename = "groupMember")]
    pub group_member: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "line")]
    pub line: i32,
    #[serde(rename = "keyType")]
    pub key_type: crate::models::KeyType,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "locked")]
    pub locked: bool,
}

impl NewPhoneKey {
    pub fn new(key_group: String, group_member: String, label: String, line: i32, key_type: crate::models::KeyType, value: String, locked: bool) -> NewPhoneKey {
        NewPhoneKey {
            key_group,
            group_member,
            label,
            line,
            key_type,
            value,
            locked,
        }
    }
}


