/*
 * Phone Backend
 *
 * ## API for managing phones connected to P7M cloud PBX  The purpose of this API is mainly to manage the configuration of phones that use P7M auto provisioning.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PhoneType {
    #[serde(rename = "phoneTypeId")]
    pub phone_type_id: String,
    #[serde(rename = "typeName")]
    pub type_name: String,
    #[serde(rename = "lastChange")]
    pub last_change: String,
}

impl PhoneType {
    pub fn new(phone_type_id: String, type_name: String, last_change: String) -> PhoneType {
        PhoneType {
            phone_type_id,
            type_name,
            last_change,
        }
    }
}


